---
title: "Exercise №1"
format:
    md:
        output-file: readme.md
editor: visual
---

## Цель Работы

1.  Изучить возможности технологии Yandex Query для анализа структурированных наборов данных
2.  Получить навыки построения аналитического пайплайна для анализа данных с помощью сервисов Yandex Cloud
3.  Закрепить практические навыки использования SQL для анализа данных сетевой активности в сегментированной корпоративной сети

## Ход работы

## Задание 1

### Известно, что IP адреса внутренней сети начинаются с октетов, принадлежащих интервалу \[12-14\]. Определите количество хостов внутренней сети, представленных в датасете.

```{}
SELECT count(distinct src) as counts
FROM yaqry1mdataset
WHERE
    (src REGEXP '(^1[2-4].*)')
```

### Ответ: 1000

## Задание 2

### Определите суммарный объем исходящего трафика

```{}
SELECT SUM(bytes) as amount FROM yaqry1mdataset ls WHERE NOT (ls.dst REGEXP '(^1[2-4].*)')
```

### Ответ: 6726396441

## Задание 3

### Определите суммарный объем входящего трафика

```{}
SELECT SUM(bytes) as amount FROM yaqry1mdataset ls WHERE NOT (ls.src REGEXP '(^1[2-4].*)')
```

### Ответ: 12459379906

```{r}
sprintf("The end")
```

## Вывод

Изучил возможности Yandex Query и закрепил навыки использования SQL для анализа данных сетевой активности
